# Generated by Django 2.2.4 on 2019-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minerals',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
